/**
 * FIELD ERRORS (error codes for errorResponse.details)
 */
export const REQUIRED_INPUT_ERROR = 'REQUIRED';
export const LENGTH_INPUT_ERROR = 'INVALID_LENGTH';
export const PHONE_INPUT_ERROR = 'INVALID_PHONE';
export const PAYMENT_METHOD_INPUT_ERROR = 'INVALID_PAYMENT_METHOD';
export const ID_INPUT_ERROR = 'INVALID_ID';
export const DUPLICATED_VALUE_INPUT_ERROR = 'DUPLICATED';
export const NOT_ALLOWED_INPUT_ERROR = 'NOT_ALLOWED';
export const NOT_EXIST_INPUT_ERROR = 'NOT_EXISTED';
export const MIN_INPUT_ERROR = 'INVALID_MINIMUM_VALUE';
export const MAX_INPUT_ERROR = 'INVALID_MAXIMUM_VALUE';
export const PASSWORD_INPUT_ERROR = 'PASSWORD_INPUT_ERROR';
